# Generated by Django 4.2.10 on 2024-05-15 08:53

import django.utils.timezone
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
