# Generated by Django 4.2.10 on 2024-05-15 09:25

from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0002_alter_collect_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collect",
            old_name="author",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="collect",
            name="image",
            field=models.ImageField(blank=True, upload_to="collect_images/"),
        ),
    ]
