# Generated by Django 4.2.10 on 2024-05-20 18:14

from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0004_remove_collect_current_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "subject",
                    models.CharField(
                        default="Новый {{ event }} на сумму {{ amount }}.",
                        max_length=255,
                    ),
                ),
                ("body", models.TextField()),
                ("is_html", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Шаблон письма",
                "verbose_name_plural": "Шаблоны писем",
            },
        ),
    ]
