# Generated by Django 4.2.10 on 2024-05-20 20:20

from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0006_rename_planned_amount_collect_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
