volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"

  backend:
    build: ../backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file: ../.env
    volumes:
      - static:/app/staticfiles
      - media:/app/mediafiles
    depends_on:
      - db
      - redis

  celery:
    build: ../backend
    command: celery -A config worker -l INFO
    env_file: ../.env
    depends_on:
      - backend
      - redis

  nginx:
    image: nginx:1.19.3
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - static:/static
       - media:/media
    ports:
      - "80:80"
    depends_on:
      - backend


